### PR TITLE
Small fixes and Django 2.0

### PR DESCRIPTION
**Pull request by vdboor**
Hi @bashu! I've made a few small changes, including one for Django 2.0 support. Feel free to merge these.

If you like, I can also invite you to the django-fluent organization, so you can migrate this repository over there.

### CODE REVIEW

**Comment by bashu** [comment]
@vdboor can you rebase PR on the working "develop" branch ?

**Comment by vdboor** [comment]
No problem, you can find the changes in #4 now. (since I didn't want to rebase my master on develop)

**Comment by bashu** [comment]
@vdboor answering your question, yes sure!

**Comment by vdboor** [comment]
@bashu : wonderful! You've got an invitation

**Pull request closed without merging**
